version: "3"
services:
  payment-service:
    build: .
    container_name: payment-service_data
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27018/payment_db?authSource=admin
      - KAFKA_BROKER=kafka:29092
    networks:
      - app-network
    depends_on:
      - mongodb
      - kafka

networks:
  app-network:
    external: true
