version: "3"
services:
  billing-service:
    build: .
    container_name: billing-service_data
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27018/billing_db?authSource=admin
      - KAFKA_BROKER=kafka:29092
    networks:
      - app-network
    depends_on:
      - mongodb
      - kafka

networks:
  app-network:
    external: true
